blank_issues_enabled: false
contact_links:
  - name: Questions or Discussions
    url: https://github.com/sdurutr436/ProyectoIntermodular-MapaInteractivo/discussions
    about: Use discussions for general questions and project discussions
